language: node_js # 声明构建语言环境
node_js:
  - "6"

branches:
  only:
  - master

notifications:      # 每次构建的时候是否通知，如果不想收到通知邮箱（个人感觉邮件贼烦），那就设置false吧
  email: false

sudo: false         # 开启基于容器的Travis CI任务，让编译效率更高。

before_script: npm install
script: npm run test



